In [1]:
print("Hello world")

Hello world

In [2]:
import pandas as pd

In [14]:
s1 = pd.Series(["Banana" , "apple" , "cherries" , "leachi"],  index=[10 , 20 , 14 , 30], name="fruits")

In [15]:
s1

10      Banana
20       apple
14    cherries
30      leachi
Name: fruits, dtype: object

In [16]:
s1[20]

'apple'

In [6]:
s2 = pd.Series(data = [10 , 20 , 14 , 30],  index=["Banana" , "apple" , "cherries" , "leachi"])

In [7]:
s2

Banana      10
apple       20
cherries    14
leachi      30
dtype: int64

In [11]:
s2[0]

C:\Users\HP\AppData\Local\Temp\ipykernel_16456\2344841457.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s2[0]

np.int64(10)

In [10]:
s2.loc["Banana"]

np.int64(10)

In [13]:
s2.iloc[1]

np.int64(20)

In [17]:
s1

10      Banana
20       apple
14    cherries
30      leachi
Name: fruits, dtype: object

In [29]:
s1.iloc[1:3]

20       apple
14    cherries
Name: fruits, dtype: object

In [30]:
result = {
    "Roll No" : [101 , 102 , 103 , 104 , 105 , 106 , 107 , 108 , 109 , 110],
    'Name':['Azam','Rehana','Ghaffar','Nawaz','Bilwal','Hashir', 'Maryam','Asim','Rehan','Sana'],
    'Python':[75,67,78,89,90,98,87,76,45,90],
    'Pandas':[87,78,98,91,61,73,94,85,78,90], 
    'Statistics':[89,67,89,76,78,56,54,56,78,98],
    'MachineLearning':[87,78,98,91,61,73,94,85,78,90],
    'DeepLearning':[75,67,78,89,90,98,87,76,45,90]
}
result

{'Roll No': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
 'Name': ['Azam',
  'Rehana',
  'Ghaffar',
  'Nawaz',
  'Bilwal',
  'Hashir',
  'Maryam',
  'Asim',
  'Rehan',
  'Sana'],
 'Python': [75, 67, 78, 89, 90, 98, 87, 76, 45, 90],
 'Pandas': [87, 78, 98, 91, 61, 73, 94, 85, 78, 90],
 'Statistics': [89, 67, 89, 76, 78, 56, 54, 56, 78, 98],
 'MachineLearning': [87, 78, 98, 91, 61, 73, 94, 85, 78, 90],
 'DeepLearning': [75, 67, 78, 89, 90, 98, 87, 76, 45, 90]}

In [34]:
result = pd.DataFrame(result)
result

   Roll No     Name  Python  Pandas  Statistics  MachineLearning  DeepLearning
0      101     Azam      75      87          89               87            75
1      102   Rehana      67      78          67               78            67
2      103  Ghaffar      78      98          89               98            78
3      104    Nawaz      89      91          76               91            89
4      105   Bilwal      90      61          78               61            90
5      106   Hashir      98      73          56               73            98
6      107   Maryam      87      94          54               94            87
7      108     Asim      76      85          56               85            76
8      109    Rehan      45      78          78               78            45
9      110     Sana      90      90          98               90            90

In [37]:
result["Total"] = (result.Python) + (result.Pandas) + (result.Statistics) + (result.MachineLearning) + (result.DeepLearning)

In [38]:
result

,Roll No,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total
0,101,Azam,75,87,89,87,75,413
1,102,Rehana,67,78,67,78,67,357
2,103,Ghaffar,78,98,89,98,78,441
3,104,Nawaz,89,91,76,91,89,436
4,105,Bilwal,90,61,78,61,90,380
5,106,Hashir,98,73,56,73,98,398
6,107,Maryam,87,94,54,94,87,416
7,108,Asim,76,85,56,85,76,378
8,109,Rehan,45,78,78,78,45,324
9,110,Sana,90,90,98,90,90,458

In [43]:
result["Percentage"] = result.Total / 500 * 100

In [46]:
result

,Roll No,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage
0,101,Azam,75,87,89,87,75,413,82.6
1,102,Rehana,67,78,67,78,67,357,71.4
2,103,Ghaffar,78,98,89,98,78,441,88.2
3,104,Nawaz,89,91,76,91,89,436,87.2
4,105,Bilwal,90,61,78,61,90,380,76.0
5,106,Hashir,98,73,56,73,98,398,79.6
6,107,Maryam,87,94,54,94,87,416,83.2
7,108,Asim,76,85,56,85,76,378,75.6
8,109,Rehan,45,78,78,78,45,324,64.8
9,110,Sana,90,90,98,90,90,458,91.6

In [47]:
result["Grade"] = "A"

In [48]:
result

,Roll No,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade
0,101,Azam,75,87,89,87,75,413,82.6,A
1,102,Rehana,67,78,67,78,67,357,71.4,A
2,103,Ghaffar,78,98,89,98,78,441,88.2,A
3,104,Nawaz,89,91,76,91,89,436,87.2,A
4,105,Bilwal,90,61,78,61,90,380,76.0,A
5,106,Hashir,98,73,56,73,98,398,79.6,A
6,107,Maryam,87,94,54,94,87,416,83.2,A
7,108,Asim,76,85,56,85,76,378,75.6,A
8,109,Rehan,45,78,78,78,45,324,64.8,A
9,110,Sana,90,90,98,90,90,458,91.6,A

In [51]:
result

,Roll No,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage
0,101,Azam,75,87,89,87,75,413,82.6
1,102,Rehana,67,78,67,78,67,357,71.4
2,103,Ghaffar,78,98,89,98,78,441,88.2
3,104,Nawaz,89,91,76,91,89,436,87.2
4,105,Bilwal,90,61,78,61,90,380,76.0
5,106,Hashir,98,73,56,73,98,398,79.6
6,107,Maryam,87,94,54,94,87,416,83.2
7,108,Asim,76,85,56,85,76,378,75.6
8,109,Rehan,45,78,78,78,45,324,64.8
9,110,Sana,90,90,98,90,90,458,91.6

In [53]:
result["Grade"] = ["A" , "B" , "A+" , "C" , "A" , "B+" , "D" , "A" , "B" , "A+"]

In [54]:
result

,Roll No,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade
0,101,Azam,75,87,89,87,75,413,82.6,A
1,102,Rehana,67,78,67,78,67,357,71.4,B
2,103,Ghaffar,78,98,89,98,78,441,88.2,A+
3,104,Nawaz,89,91,76,91,89,436,87.2,C
4,105,Bilwal,90,61,78,61,90,380,76.0,A
5,106,Hashir,98,73,56,73,98,398,79.6,B+
6,107,Maryam,87,94,54,94,87,416,83.2,D
7,108,Asim,76,85,56,85,76,378,75.6,A
8,109,Rehan,45,78,78,78,45,324,64.8,B
9,110,Sana,90,90,98,90,90,458,91.6,A+

In [55]:
del result["Grade"]

In [56]:
result

,Roll No,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage
0,101,Azam,75,87,89,87,75,413,82.6
1,102,Rehana,67,78,67,78,67,357,71.4
2,103,Ghaffar,78,98,89,98,78,441,88.2
3,104,Nawaz,89,91,76,91,89,436,87.2
4,105,Bilwal,90,61,78,61,90,380,76.0
5,106,Hashir,98,73,56,73,98,398,79.6
6,107,Maryam,87,94,54,94,87,416,83.2
7,108,Asim,76,85,56,85,76,378,75.6
8,109,Rehan,45,78,78,78,45,324,64.8
9,110,Sana,90,90,98,90,90,458,91.6

# List comprehension

In [57]:
result["Grade"] = ["A+" if p >= 90
                   else "A" if p >= 80
                   else "B" if p >= 70
                   else "C" if p >= 60
                   else "D" if p >= 50
                   else "F"
                   for p in result.Percentage]

In [58]:
result

,Roll No,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade
0,101,Azam,75,87,89,87,75,413,82.6,A
1,102,Rehana,67,78,67,78,67,357,71.4,B
2,103,Ghaffar,78,98,89,98,78,441,88.2,A
3,104,Nawaz,89,91,76,91,89,436,87.2,A
4,105,Bilwal,90,61,78,61,90,380,76.0,B
5,106,Hashir,98,73,56,73,98,398,79.6,B
6,107,Maryam,87,94,54,94,87,416,83.2,A
7,108,Asim,76,85,56,85,76,378,75.6,B
8,109,Rehan,45,78,78,78,45,324,64.8,C
9,110,Sana,90,90,98,90,90,458,91.6,A+

# Lambda functinos

In [63]:
result["Grade1"] = result.Percentage.apply(lambda p:"A+" if p >= 90
                   else "A" if p >= 80
                   else "B" if p >= 70
                   else "C" if p >= 60
                   else "D" if p >= 50
                   else "F")

In [64]:
result

,Roll No,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade,Grade1
0,101,Azam,75,87,89,87,75,413,82.6,A,A
1,102,Rehana,67,78,67,78,67,357,71.4,B,B
2,103,Ghaffar,78,98,89,98,78,441,88.2,A,A
3,104,Nawaz,89,91,76,91,89,436,87.2,A,A
4,105,Bilwal,90,61,78,61,90,380,76.0,B,B
5,106,Hashir,98,73,56,73,98,398,79.6,B,B
6,107,Maryam,87,94,54,94,87,416,83.2,A,A
7,108,Asim,76,85,56,85,76,378,75.6,B,B
8,109,Rehan,45,78,78,78,45,324,64.8,C,C
9,110,Sana,90,90,98,90,90,458,91.6,A+,A+

# Outline function

In [67]:
def Grading_system(p):
        if p >= 90:
            return "A+"
        elif p >= 80:
            return "A"
        elif p >= 70:
            return "B"
        elif p >= 60:
            return "C"
        elif p >= 50:
            return "D"
        else:
            return "F"
result["Grade2"] = result.Percentage.apply(Grading_system)

In [68]:
result

,Roll No,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade,Grade1,Grade2
0,101,Azam,75,87,89,87,75,413,82.6,A,A,A
1,102,Rehana,67,78,67,78,67,357,71.4,B,B,B
2,103,Ghaffar,78,98,89,98,78,441,88.2,A,A,A
3,104,Nawaz,89,91,76,91,89,436,87.2,A,A,A
4,105,Bilwal,90,61,78,61,90,380,76.0,B,B,B
5,106,Hashir,98,73,56,73,98,398,79.6,B,B,B
6,107,Maryam,87,94,54,94,87,416,83.2,A,A,A
7,108,Asim,76,85,56,85,76,378,75.6,B,B,B
8,109,Rehan,45,78,78,78,45,324,64.8,C,C,C
9,110,Sana,90,90,98,90,90,458,91.6,A+,A+,A+